
name: 'coretelecoms'
version: '1.0.0'
config-version: 2

profile: 'coretelecoms'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  coretelecoms:
    staging:
      +materialized: view
    marts:
      +materialized: table