FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /dbt

RUN pip install --no-cache-dir dbt-snowflake==1.8.0

COPY dbt/ .

CMD ["dbt", "debug"]